### ISSUE TITLE
UNRESOLVED DEPENDENCY

### ISSUE THREAD

**Issue by loicknuchel** [cloudinary/cloudinary_scala#13]
Hi,

I tried to include this lib on my project but I got UNRESOLVED DEPENDENCY :(

```
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/cloudinary/cloudinary-core-scala_2.10/0.9.7-SNAPSHOT/cloudinary-core-scala_2.10-0.9.7-SNAPSHOT.pom
[warn] ==== Typesafe Releases Repository: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/cloudinary/cloudinary-core-scala_2.10/0.9.7-SNAPSHOT/cloudinary-core-scala_2.10-0.9.7-SNAPSHOT.pom
[warn] ==== Sonatype snapshots: tried
[warn]   http://oss.sonatype.org/content/repositories/snapshots/com/cloudinary/cloudinary-core-scala_2.10/0.9.7-SNAPSHOT/cloudinary-core-scala_2.10-0.9.7-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.cloudinary#cloudinary-core-scala_2.10;0.9.7-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

For info, I added `"com.cloudinary" %% "cloudinary-core-scala" % "0.9.7-SNAPSHOT"` as dependency and `"Sonatype snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"` as resolver.
I use Play 2.2.3 with scala 2.10.3

Thanks for help :)

**Comment by itaibenari** [comment]
Is it possible to upgrade your version of Scala to 2.10.4 an try again?
We're looking at changing the dependency to be lower than 2.10.4.

**Comment by tocker** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support [http://support.cloudinary.com](http://support.cloudinary.com) or create a new ticket if you have any additional issues.
