### ISSUE TITLE
CloudinaryPlugin Constructor Issue

### ISSUE THREAD

**Issue by kaning** [cloudinary/cloudinary_scala#16]
Using play framework 2.4 this is the exception I get when I try to do something like 

@url("sample", Set('transformation -> Transformation().width(100).height(100).crop("fill"), 'format -> "png"))

ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in cloudinary.plugin.CloudinaryPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at cloudinary.plugin.CloudinaryPlugin.class(CloudinaryPlugin.scala:13)
  while locating cloudinary.plugin.CloudinaryPlugin

**Comment by premosystems** [comment]
I am also having this error.

**Comment by itaibenari** [comment]
@kaning, @premosystems 
please try using the play_2_4 branch. see if it fixes things for you. we'll be releasing it in a more official way soon.

**Comment by kaning** [comment]
@itaibenari I have tried the sbt publishLocal but i bombs out on trying to compile because it cannot find SonatypeKeys.

**Comment by itaibenari** [comment]
@kaning This part is used for publishing artifacts publically. You can just remove that part from sbt (and any other related thing) and try again.
