### ISSUE TITLE
Update to support Scala 2.13

### ISSUE THREAD

**Issue by Swissbite** [cloudinary/cloudinary_scala#33]
Currently, the library is not cross-built with scala 2.13

Scala 2.13 has been released 2019. Two years later, there is no build for scala 2.13.

**Comment by roeeba** [comment]
Hi @Swissbite,

After careful consideration, Cloudinary has decided to deprecate its Scala SDK. This SDK will no longer be maintained, with the exception of any high-priority regression bugs that may arise.
A deprecation notice will be added to the Scala Readme soon.
Cloudinary offers many other actively maintained SDKs that are used by many Cloudinary customers. We recommend that you switch to one of these. For details and complete documentation on all available SDKs, please see our [Cloudinary SDK Guides](https://cloudinary.com/documentation/cloudinary_sdks).
We apologize for any inconvenience this may cause. Please feel free to [reach out to our support team](https://support.cloudinary.com/hc/en-us/requests/new) with any questions you may have.
