### ISSUE TITLE
Missing support for Play 2.3

### ISSUE THREAD

**Issue by jgrape** [cloudinary/cloudinary_scala#7]
I'm upgrading from Play 2.2.2 to Play 2.3.7 and I get stuck on a missing dependency:
```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.cloudinary#cloudinary-scala-play_2.11;0.9.3-SNAPSHOT: not found
```
Looking in the Sonatype snapshots repo I can see that the core bits are compiled for both Scala 2.10 and 2.11, but the Play plugin is only compiled for Scala 2.10 (which is used in Play 2.2.2) and not for Scala 2.11 (which is used in Play 2.3.7)

**Comment by itaibenari** [comment]
Released cross compiled play plugin. Please see if this solves the issue for you

**Comment by jgrape** [comment]
Confirmed that 0.9.6-SNAPSHOT compiles and runs with Play Framework 2.3.7
