### ISSUE TITLE
CloudinaryPlugin should support CLOUDINARY_URL

### ISSUE THREAD

**Issue by jgrape** [cloudinary/cloudinary_scala#9]
Today the CloudinaryPlugin is configured by a number of properties set in the application.conf. Yet, outside Play (in cloudinary-core-scala) a Cloudinary instance can be created from only one variable - the CLOUDINARY_URL.

It would be great in the Play plugin could be configured using the CLOUDINARY_URL.

One way of achieving this would be to allow the plugin to be initiated using a single property *cloudinary.url* in application.conf.

In application.conf, the environment variable CLOUDINARY_URL can be picked up using:
```
cloudinary.url = ${?CLOUDINARY_URL}
```
This would work perfectly with the Cloudinary Heroku addon, since it automatically sets this environment variable.

**Comment by tocker** [comment]
Hi @jgrape,

Thanks for your request.
This feature has been added in version 0.9.7.

Please contact our support if you have any other issue.
